export const GET_RECIPES_REQUEST = "GET_RECIPES_REQUEST";
export const GET_RECIPES_SUCCESS = "GET_RECIPES_SUCCESS";
export const GET_RECIPES_FAILURE = "GET_RECIPES_FAILURE";

export const CREATE_RECIPE_REQUEST = "CREATE_RECIPE_REQUEST";
export const CREATE_RECIPE_SUCCESS = "CREATE_RECIPE_SUCCESS";
export const CREATE_RECIPE_FAILURE = "CREATE_RECIPE_FAILURE";

export const REMOVE_RECIPE_REQUEST = "REMOVE_RECIPE_REQUEST";
export const REMOVE_RECIPE_SUCCESS = "REMOVE_RECIPE_SUCCESS";
export const REMOVE_RECIPE_FAILURE = "REMOVE_RECIPE_FAILURE";

export const MODIFY_RECIPE_REQUEST = "MODIFY_RECIPE_REQUEST";
export const MODIFY_RECIPE_SUCCESS = "MODIFY_RECIPE_SUCCESS";
export const MODIFY_RECIPE_FAILURE = "MODIFY_RECIPE_FAILURE";
